# Generated by Django 4.2.11 on 2026-01-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("income", "Entrada"), ("outcome", "Saída")],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Movimentação de Caixa",
                "verbose_name_plural": "Movimentações de Caixa",
            },
        ),
        migrations.CreateModel(
            name="CashSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Saldo Inicial",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Saldo Final",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Aberto"), ("closed", "Fechado")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Sessão de Caixa",
                "verbose_name_plural": "Sessões de Caixa",
            },
        ),
    ]
